#!/usr/bin/env python3
"""v2 interaction regression suite; see harness_v2.py for fixture limitations."""
import json
import os
from pathlib import Path
from playwright.sync_api import sync_playwright
from harness_v2 import ROOT, prepare
ART=Path(os.environ.get('DIAMOND_TEST_ARTIFACTS', str(ROOT/'artifacts'/'v2-regression-v3'))); ART.mkdir(exist_ok=True)
checks=[]
def check(value,name):
    assert value,name
    checks.append(name)
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1360,'height':1000})
    errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    prepare(page)
    check(page.locator('.pad').count()==64 and page.locator('.pad:not(:disabled)').count()==13,'64 diamond pads, 13 playable')
    check(page.locator('#instrument').is_visible() and page.locator('#piano-panel').is_hidden(),'Diamond is the default single view')
    check(page.locator('#instrument').bounding_box()['width']>1250,'Diamond panel spans desktop width')
    check(page.locator('#next-note').inner_text()=='E4','Library opens with correct next pitch')
    page.locator('#pad-0-0').click()
    check(page.locator('#progress-label').inner_text().startswith('1 /'),'Wrong note does not advance')
    page.locator('#pad-2-2').click()
    page.locator('#view-piano').click()
    check(page.locator('#piano-panel').is_visible() and page.locator('#instrument').is_hidden(),'Piano is an alternate full-width view')
    check(page.locator('#piano').bounding_box()['width']>1200,'Piano keys use desktop width')
    check(page.locator('#progress-label').inner_text().startswith('2 /'),'View switch preserves lesson progress')
    page.locator('#piano-2-2').click()
    check(page.locator('#next-note').inner_text()=='F4','Piano advances the same repeated-note lesson')
    page.locator('#simple-mode').click()
    check(page.locator('.topbar').is_hidden() and page.locator('.practice-panel').is_hidden() and page.locator('#restore-controls').is_visible(),'Simple mode hides controls with a visible return button')
    page.locator('#piano-3-3').click()
    check('G4' in page.locator('#simple-next').inner_text(),'Piano plays and advances in simple mode')
    check(page.evaluate("new URL(__testURL).searchParams.get('simple')==='1'"),'Simple state is reflected in URL')
    page.keyboard.press('m')
    check(page.locator('.topbar').is_visible(),'M restores controls without reloading')
    page.keyboard.press('v')
    check(page.locator('#instrument').is_visible(),'V changes the active keyboard')
    page.locator('#simple-mode').click(); page.keyboard.press('Escape')
    check(page.locator('.topbar').is_visible(),'Escape restores controls')
    # No sounding notes survive a view change.
    page.locator('#pad-4-4').dispatch_event('pointerdown',{'pointerId':77,'pointerType':'touch','button':0})
    page.locator('#view-piano').click()
    check(page.locator('.pressed').count()==0,'View switch releases held notes')
    page.locator('#connect').click()
    page.wait_for_function("document.getElementById('connection-badge').textContent==='MIDI input connected'")
    check(page.evaluate('__sent.length')==0,'Connect alone sends no unsolicited MIDI')
    page.locator('#profile').select_option('mini')
    page.locator('#programmer').click();page.wait_for_timeout(120)
    check(page.evaluate('__sent.some(x=>JSON.stringify(x.bytes)===JSON.stringify([240,0,32,41,2,13,14,1,247]))'),'Mini Programmer command remains supported')
    page.locator('#restart').click()
    page.locator('#map-controller').click()
    check(page.locator('#mapping-dialog').is_visible(),'Mapping editor is reachable from primary toolbar')
    before=page.evaluate('__sent.filter(x=>x.bytes[0]===240).length')
    page.locator('#map-learn-all').click()
    page.evaluate('__midi([146,36,100]);__midi([146,36,100])')
    check(page.locator('#map-row-0-0 input[data-field=note]').input_value()=='36','Wizard learns incoming note')
    check(page.locator('#map-row-0-0 input[data-field=channel]').input_value()=='3','Wizard learns actual input channel')
    check(page.locator('#map-row-1-1 input[data-field=note]').input_value()=='','Held/repeated note-on cannot fill the next mapping slot')
    page.evaluate('__midi([130,36,0]);__midi([146,36,100]);__midi([130,36,0])')
    check('already assigned' in page.locator('#map-message').inner_text(),'Duplicate note/channel assignments are rejected')
    for n in range(37,49):page.evaluate(f'__midi([146,{n},100]);__midi([130,{n},0])')
    check('Learning finished' in page.locator('#map-message').inner_text(),'All thirteen roles are learned')
    check(page.locator('#progress-label').inner_text().startswith('1 /'),'Calibration MIDI does not advance the lesson')
    check(page.evaluate('__sent.filter(x=>x.bytes[0]===240).length')==before,'Calibration does not change hardware mode')
    # White E is the third role in the white-first learning order.
    page.locator('#map-row-2-2 input[data-field=ledNote]').fill('99')
    page.locator('#map-row-2-2 input[data-field=ledChannel]').fill('5')
    page.locator('#map-row-2-2 button[aria-label="Test LED for E4"]').click()
    check(page.evaluate('__sent.some(x=>x.port==="led"&&JSON.stringify(x.bytes)===JSON.stringify([148,99,37]))'),'Per-key LED test uses its independent note and channel')
    page.wait_for_timeout(730)
    check(page.evaluate('__sent.some(x=>x.port==="led"&&JSON.stringify(x.bytes)===JSON.stringify([132+16,99,0]))'),'LED test sends a timed off message')
    page.locator('#map-apply').click()
    check(page.locator('#mapping-dialog').is_hidden() and page.locator('#profile').input_value()=='custom','Apply activates the custom map')
    saved=page.evaluate("JSON.parse(__storage['diamond-v1'])")
    check(saved['custom']['2-2']=={'note':38,'channel':2,'ledNote':99,'ledChannel':4},'Custom input and LED mappings persist separately')
    page.locator('#lights').click()
    check(page.evaluate('__sent.some(x=>x.port==="led"&&JSON.stringify(x.bytes)===JSON.stringify([148,99,37]))'),'Piano view still drives mapped Launchpad lights')
    page.locator('#midi-synth').select_option('synth')
    page.evaluate('__midi([144,38,100]);__midi([128,38,0])')
    check(page.locator('#progress-label').inner_text().startswith('1 /'),'Mapped input channel is respected')
    page.evaluate('__midi([146,38,100]);__midi([130,38,0])')
    check(page.locator('#progress-label').inner_text().startswith('2 /'),'Custom physical input advances the shared piano lesson')
    check(page.evaluate('__sent.some(x=>x.port==="synth"&&x.bytes[0]===144&&x.bytes[1]===64)'), 'Sound MIDI output receives musical E4, not learned address 38 or LED address 99')
    check(page.evaluate('__sent.some(x=>x.port==="synth"&&x.bytes[0]===128&&x.bytes[1]===64)'), 'Custom MIDI input gets a matched synth note-off')
    page.locator('#midi-synth').select_option('')
    page.locator('#map-controller').click();page.locator('#map-learn-all').click()
    page.evaluate('__midi([144,12,90]);__midi([144,12,0])')
    page.locator('#map-cancel').click()
    check(page.evaluate("JSON.parse(__storage['diamond-v1']).custom['0-0'].note") ==36,'Cancel discards draft and preserves the working map')
    page.locator('#map-controller').click();page.locator('#map-pad-0-0').click()
    page.evaluate('__midi([145,55,110]);__midi([129,55,0])')
    page.locator('#map-apply').click()
    check(page.evaluate("JSON.parse(__storage['diamond-v1']).custom['0-0'].note") ==55,'Single-key repair does not require relearning all pads')
    page.locator('#map-controller').click()
    with page.expect_download() as download:page.locator('#map-export').click()
    export=download.value.path().read_text()
    check(json.loads(export)['format']=='diamond-pad-map','Mapping export produces portable JSON')
    page.locator('#map-import').set_input_files({'name':'bad.json','mimeType':'application/json','buffer':b'{}'})
    page.wait_for_timeout(100)
    check('13' in page.locator('#map-message').inner_text(),'Incomplete imports are rejected')
    page.locator('#map-import').set_input_files({'name':'map.json','mimeType':'application/json','buffer':export.encode()})
    page.wait_for_function("document.getElementById('map-message').textContent.includes('Imported 13')")
    check(page.locator('#map-row-2-2 input[data-field=ledNote]').input_value()=='99','JSON import restores custom LED data')
    page.locator('#map-cancel').click()
    # Chord collection remains shared across presentations.
    page.locator('#song-select').select_option('diamond-chords')
    page.wait_for_function("document.getElementById('song-title').textContent==='Diamond Chords'")
    page.locator('#reading').select_option('chords')
    page.locator('#piano-0-0').click();page.locator('#view-diamond').click()
    page.locator('#pad-2-2').click();page.locator('#pad-4-4').click()
    check(page.locator('#progress-label').inner_text().startswith('2 /'),'Partial chord collection survives a view change')
    page.locator('#song-select').select_option('ode-to-joy')
    page.wait_for_function("document.getElementById('song-title').textContent==='Ode to Joy'")
    page.locator('#reading').select_option('melody')
    page.locator('#transpose').fill('12');page.locator('#transpose').dispatch_event('change')
    check(page.locator('#range-label').inner_text()=='C5 — C6','Automatic octave following remains active')
    page.locator('#range-mode').select_option('fixed')
    check(page.locator('#next-label').inner_text()=='OUTSIDE THIS OCTAVE','Fixed octave still reports unplayable notes')
    page.locator('#range-mode').select_option('fold')
    check(page.locator('#next-note').inner_text()=='E4','Explicit folding remains available')
    page.locator('#transpose').fill('0');page.locator('#transpose').dispatch_event('change')
    page.locator('#range-mode').select_option('follow')
    page.locator('#listen').click();page.wait_for_timeout(730)
    check(page.locator('#next-label').inner_text()=='LISTENING','Reference playback works after mapping/view changes')
    page.locator('#listen').click()
    fetches=page.evaluate('__fetches.length')
    page.locator('#file').set_input_files(str(ROOT/'library/chromatic-walk.mid'))
    page.wait_for_function("document.getElementById('song-title').textContent==='chromatic-walk'")
    check(page.evaluate('__fetches.length')==fetches,'Local MIDI import still makes no network request')
    page.locator('#file').set_input_files({'name':'broken.mid','mimeType':'audio/midi','buffer':b'broken'})
    page.wait_for_timeout(100)
    check(page.locator('#song-title').inner_text()=='chromatic-walk','Malformed MIDI preserves the current song')
    # Fresh starts exercise URL priority and restored local mapping.
    other=browser.new_page(viewport={'width':390,'height':844});other.on('pageerror',lambda e:errors.append(str(e)))
    saved=page.evaluate("JSON.parse(__storage['diamond-v1'])")
    prepare(other,'?song=ode-to-joy&view=piano&simple=1',saved)
    check(other.locator('#piano-panel').is_visible() and other.locator('#restore-controls').is_visible(),'URL opens the simple piano view directly')
    other.locator('#piano-2-2').click()
    check('2 /' in other.locator('#simple-next').inner_text(),'Touch-only simple startup is immediately playable')
    other.locator('#restore-controls').click();other.locator('#map-controller').click()
    check(other.locator('#map-row-2-2 input[data-field=ledNote]').input_value()=='99','Mapping survives a fresh page startup')
    other.locator('#map-cancel').click();other.close()
    # Layout, all playable pad hit targets and touch cancellation on common form factors.
    screen=browser.new_page(); screen.on('pageerror',lambda e:errors.append(str(e)))
    prepare(screen,'?song=ode-to-joy&view=diamond&clear=1')
    check(screen.locator('#restore-controls').is_visible(),'clear=1 alias starts minimal mode')
    for width,height in [(1360,1000),(820,1180),(390,844),(844,390)]:
        screen.set_viewport_size({'width':width,'height':height})
        check(screen.evaluate('document.documentElement.scrollWidth')==width,f'No horizontal overflow in diamond at {width}×{height}')
        bounds=screen.locator('.pad:not(:disabled)').evaluate_all('(els)=>els.every(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=68&&r.bottom<=innerHeight})')
        check(bounds,f'All 13 playable diamond pads fit at {width}×{height}')
        if width in [1360,390]:screen.screenshot(path=str(ART/f'diamond-simple-{width}-v2.png'))
        screen.keyboard.press('v')
        check(screen.evaluate('document.documentElement.scrollWidth')==width,f'No horizontal overflow in piano at {width}×{height}')
        check(screen.locator('#piano').bounding_box()['width']>=width-26,f'Piano uses available width at {width}×{height}')
        if width in [1360,390]:screen.screenshot(path=str(ART/f'piano-simple-{width}-v2.png'))
        screen.keyboard.press('v')
    screen.set_viewport_size({'width':390,'height':844})
    screen.locator('#pad-2-2').dispatch_event('pointerdown',{'pointerId':90,'pointerType':'touch','button':0})
    screen.dispatch_event('body','pointercancel',{'pointerId':90,'pointerType':'touch'})
    check(screen.locator('.pad.pressed').count()==0,'Cancelled touch releases the pad in simple mode')
    screen.locator('#restore-controls').click()
    screen.locator('#copy-practice-link').click()
    screen.wait_for_timeout(100)
    check('simple=1' in screen.locator('#practice-link').input_value(),'Share link has selectable-text fallback when clipboard is unavailable')
    screen.set_viewport_size({'width':1360,'height':1000})
    screen.screenshot(path=str(ART/'diamond-full-width-v2.png'),full_page=True)
    screen.locator('#map-controller').click();screen.screenshot(path=str(ART/'mapping-editor-v2.png'))
    check(not errors,'No uncaught browser errors')
    browser.close()
report={'version':'2.0.0','date':'2026-09-17','passed':len(checks),'failed':0,'checks':checks,
 'environment':'Headless Chromium; fixture-backed URL, storage, fetch and Web MIDI; isolated source module harness (see tests/harness_v2.py).',
 'not_tested':['Physical Launchpad or LED palette','Real iPad/iPhone/Safari hardware','Audible latency','Live network navigation (disabled in this environment)']}
(ART/'browser-verification-v2.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report,indent=2))
