// JSON is the source of truth; the generated module avoids runtime JSON-fetch races.
import {readFileSync, writeFileSync} from 'node:fs';
import {normalizeMapping} from '../src/mapping.js';
const source = new URL('../mappings/novation-launchpad.json', import.meta.url);
const output = new URL('../src/presets.js', import.meta.url);
const data = JSON.parse(readFileSync(source, 'utf8'));
const map = normalizeMapping(data.mapping, true);
const text = '// Generated by tools/generate_preset.mjs from the user-exported JSON. Do not edit.\n' +
  'export const NOVATION_PROFILE = "novation-launchpad";\n' +
  'export const NOVATION_MAPPING = Object.freeze(Object.fromEntries(Object.entries(' +
  JSON.stringify(map, null, 2) + ').map(([id, value]) => [id, Object.freeze(value)])));\n';
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== text) throw new Error('Preset is out of date. Run node tools/generate_preset.mjs.');
} else writeFileSync(output, text);
